---  
spring: 
   profiles: 
    active:
    - dev
---   
server:
  port: 7001   

spring:
  profiles: dev #开发模式
  application: 
       name: deptspringcloud-config-client-eureka
       
eureka: 
  instance:
    hostname: eureka7001.com 
  client: 
    register-with-eureka: false     # 表示自己不想注册中进行注册自己      
    fetch-registry:  false  #表示自己就是注册中心，就维护服务实例的，不需要进行检索服务
    service-url: 
       defaultZone:  http://eureka7001.com:7001/eureka/       
--- 
server:
  port: 7001  
   
spring: 
   profiles: 
    active:
    - test
---   
spring:
  profiles: test #测试模式
  application: 
       name: deptspringcloud-config-client-eureka
       
       
eureka: 
  instance:
    hostname: eureka7001.com 
  client: 
    register-with-eureka: false     # 表示自己不想注册中进行注册自己      
    fetch-registry:  false  #表示自己就是注册中心，就维护服务实例的，不需要进行检索服务
    service-url: 
       defaultZone:  http://eureka7001.com:7001/eureka/         