spring: 
  profiles: 
   active: 
    - dev
---   
server: 
  port: 7001 
  

spring: 
  profiles: dev  #开发环境
  application: 
      name: chserivcecloud-config-client-eureka-client

eureka: 
  instance:
     hostname: eureka7001.com  #eureka服务端的实例名称(host文件中的别名)
   # hostname: localhost #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      defaultZone: http://eureka7001.com:7001/eureka/    #手牵手 7001中有7002和7003
      
  
         
---
server: 
  port: 7001 

spring: 
  profiles: test  #测试环境
  application: 
      name: chserivcecloud-config-client-eureka-client
      
eureka: 
  instance:
     hostname: eureka7001.com  #eureka服务端的实例名称(host文件中的别名)
   # hostname: localhost #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      defaultZone: http://eureka7001.com:7001/eureka/    #手牵手 7001中有7002和7003
      
  